hrsh7th/vim-vsnip

- plugin/vsnip.vim
Suppress messages on command-line such as `call <SNR>62_expand_or_jump()`.
> Use <silent> with mappings

- autoload/vsnip/session/snippet/node/variable.vim
Fix that if the filename starts with dot (e.g. `.vimrc`), `TM_FILENAME_BASE` becomes an empty string.
> Fix TM_FILENAME_BASE

- autoload/vsnip/source.vim
This causes because l:json must be used after error-handling, but
catching doesn't declare.
> Fix(source.vim): Fix undefined error while snippet is empty

- autoload/vsnip/session/snippet.vim
- autoload/vsnip/session/snippet.vimspec
- autoload/vsnip/session/snippet/node/placeholder.vim
- autoload/vsnip/session/snippet/node/variable.vim
- autoload/vsnip/session/snippet/parser.vim
- autoload/vsnip/session/snippet/parser.vimspec
Hi @hrsh7th .
I used [c++ snippet that includes variable placeholder](https://github.com/one-harsh/vscode-cpp-snippets/blob/master/snippets/cpp.json#L2-L11). But, It looks something wrong...
In LSP definition, 
> When a variable is unknown (that is, its name isn't defined) the name of the variable is inserted and it is transformed into a placeholder.
So, I changed variable to placeholder when it's name is unkown.
There are two videos for the following snippet.
```json
{
"for": {
"prefix": "for",
"body": [
"for (${size_t} ${i} = ${1:0}; ${i} < ${2:length}; ${i}++)",
"{",
"	$3",
"}"
],
"description": "Code snippet for 'for' loop"
}
}
```
Before:
After:
> Fix variable

- plugin/vsnip.vim
Most of the time I just want to open the filetype snippet file.
I've added a `bang` to the commands so `VsnipOpen!` in a `.vim` file jumps directly to the `vim.json` snippet file.
> Add bang to edit commands to open first file

- autoload/vsnip/session/snippet.vim
- autoload/vsnip/session/snippet.vimspec
Hi @hrsh7th . Thanks for the nice plugin.
I used the following snippet nested together. But `++` was deleted as the image shows.
I found that `s:Snippet.normalize` join `$1${3:++}` to `$1`.
```json
{
"for statement": {
"prefix": "for",
"body": "for ${1:index} := 0; $1 < ${2:count}; $1${3:++} {\n\t$0\n}",
"description": "Snippet for a for loop"                                                                                                                   
}
}
```
> BUG: join placeholders when to use nested snippets

- README.md
- autoload/vsnip.vim
- doc/vsnip.txt
- plugin/vsnip.vim
This PR allows to add a mapping in select mode which will expand a snippet if one exists.
This Closes #49 `b)`
Example:
```json
{
"Augroup": {
"prefix": ["aug"],
"body": [
"augroup my_augroup",
"\tau!",
"\t${1:auc}",
"augroup END"
],
"description": "Augroup wrapper."
},
"Autocmd": {
"prefix": ["auc"],
"body": [ "autocmd ${1:autocmd ${2:VimEnter} ${3:*}} $0" ],
"description": "Function definition template."
}
}
```
```vim
imap <expr> <C-j>   vsnip#available(1)  ? '<Plug>(vsnip-expand)'         : '<C-j>'
" Expand selected placeholder with <C-j>
smap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>'
```
Type `aug` and then press `<C-j>`. This will expand the `aug` snippet and jump to the first tabstop with `auc` in select mode.
Now press `<C-j>` again to expand …
> Support expanding snippets from select mode

- README.md
- autoload/vsnip.vim
- doc/vsnip.txt
- plugin/vsnip.vim
This PR allows to add a mapping which will store the current visual selection as `$TM_SELECTED_TEXT` in the next expanded snippet.
This Closes #49 `a)`
Example:
```json
{
"snippet": {
"prefix": ["au"],
"body": [ "autocmd $TM_SELECTED_TEXT" ],
"description": "Example for selected text"
}
}
```
```vim
xmap        <C-l>  <Plug>(vsnip-set-selected-text)
imap <expr> <C-l>  vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'
```
- Now you can select some text in visual mode.
- Press `<C-l>`. This will store the text in vsnip, remove the text and
place you in insert mode.
- Now type `au` and press `<C-l>` again.
The result will be `autocmd your visual selected text here`.
Caveat: `Ctrl-v` (Visual Block) is not yet supported. I'm not sure how
the text should be concatenated.
> Add visual mode mapping to set selection as $TM_SELECTED_TEXT

- autoload/vsnip.vim
- doc/vsnip.txt
- plugin/vsnip.vim
Fixes #62
This PR aims to improve prefix detection at snippet expansion.
And this PR has a breaking change that is removing `auto_select_trigger` feature.
In my knowledge, there are no users of using this feature.
If someone raises the request to leave this feature, I will re-implement it.
> Strict prefix matching

- autoload/vsnip.vim
- autoload/vsnip/session.vim
- plugin/vsnip.vim
A recent commit introduced a regression for the newly introduced
<Plug>(vsnip-expand) mapping. (#51)
I've changed a few spots to make this mapping more robust.
The context for the snippet was detected incorrectly as the current
column was at the beginning of the selection and no snippet could be
detected.
Now the selected text will have the cursor at the end instead of the
front.
This change will probably affect no user and eases the
implementation.
Also the column offset in select mode is 1 instead of 2.
Now the implementation of <Plug>(vsnip-expand) should be fully supported
instead of "just works".
> Fix smap <Plug>(vsnip-expand)

- README.md
- autoload/vsnip.vim
- autoload/vsnip/session.vim
- autoload/vsnip/session/snippet.vim
- autoload/vsnip/session/snippet.vimspec
- autoload/vsnip/session/snippet/node.vim
- autoload/vsnip/session/snippet/node/placeholder.vim
- autoload/vsnip/session/snippet/parser.vim
- autoload/vsnip/session/snippet/parser.vimspec
- autoload/vsnip/session/snippet/parser/combinator.vim
- autoload/vsnip/source.vim
- autoload/vsnip/source/vscode.vim
- doc/vsnip.txt
- plugin/vsnip.vim
- Join `search candidates` and `narrowing candidates` to one pass.
- Separate `initialize` related codes to `s:Snippet.init`
- Avoid traverse twice.
- Avoid creating needless text_edits 
https://github.com/hrsh7th/vim-vsnip/pull/60/files?w=1
> Improve performance

- autoload/vsnip.vim
Follow up to #64 
I hadn't tested with a character after the cursor.
Should work as expected now:
`_prefix|_` now expands in insert
`_|prefix|_` still expands in select
_noprefix|_ still jumps in insert
_|noprefix|_ still jumps in select
> Fix context for select mode

- README.md
- autoload/vsnip.vim
- doc/vsnip.txt
The current suggested key mappings have an issue as they test for jump
and expansion.
```viml
imap <expr> <C-j>   vsnip#available(1)  ? '<Plug>(vsnip-expand)'         : '<TAB>'
imap <expr> <C-l>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<TAB>'
```
Inside of an expanded snippet:
`___noprefix|<C-j>` -> `___noprefix|`
`___noprefix|<C-l>` -> `___noprefix    |`
```viml
imap <expr> <Tab>   vsnip#available(1)  ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
```
`___prefix|<TAB>` -> `___prefix|`
```viml
imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
```
`___prefix|<TAB>` -> `___prefix    |`
> Improve suggested key mappings

- .themisrc
- autoload/vsnip.vim
- autoload/vsnip.vimspec
- autoload/vsnip/session.vim
- misc/global.json
- plugin/vsnip.vim
Currently, vsnip uses `s:map` utility to normalize insert-mode offset/virtual-mode offset, etc.
But I have noticed it was the wrong decision.
Because vsnip's suggested key mapping is `imap <expr><C-l> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-l>'`.
The `vsnip#expandable` call is not using `s:map`.
So I thought should be better to add the ability of mode aware `vsnip#get_context`.
> Improve get_context implementation

- .themisrc
- autoload/vsnip.vim
- autoload/vsnip/source.vim
- autoload/vsnip/source/user_snippet.vim
- autoload/vsnip/source/vscode.vim
- doc/vsnip.txt
- misc/javascript.json
- misc/vscode/package.json
- misc/vscode/vim.json
- plugin/vsnip.vim
- spec/autoload/vsnip/source.vimspec
Implement https://github.com/hrsh7th/vim-vsnip/issues/81
This PR has breaking change.
The `javascript.tsx` filetype now on interpretated as `['javascript.tsx']` instead of `['javascript`, 'tsx']`.
> [Breaking change] Add `g:vsnip_filetypes` variable

- README.md
- autoload/vsnip/snippet/node/variable.vim
- autoload/vsnip/variable.vim
- doc/vsnip.txt
- misc/global.json
- spec/plugin/vsnip.vimspec
This PR is simplified version of #94.
The omitted feature is the variable resolving at every synchronization.
For example, #95 can create `$BORDER` custom variable but this not.
However, I think the feature is too rich so this PR is reasonable too.
>  Implement custom variable register api (simple version)

- autoload/vsnip/indent.vim
- autoload/vsnip/session.vim
- autoload/vsnip/snippet.vim
- autoload/vsnip/snippet/node/variable.vim
- autoload/vsnip/variable.vim
- misc/integration.json
- plugin/vsnip.vim
- spec/autoload/vsnip/indent.vimspec
- spec/plugin/vsnip.vimspec
This PR aims to fix #86 
This PR will fix $TM_SELECTED_TEXT via the two steps.
```jsx
function foo() {
return (@<div>
<span>nickname</span>
</div>@);
}
```
If the user select text between `@` and `@`, this PR will fix text as below.
```html
<div>
<span>nickname</span>
</div>
```
```
<$1>
\t$TM_SELECTED_TEXT
</$1>
```
When using the example snippet, this PR will fix text as below.
```
<div>
<span>nickname</span>
</div>
```
Currently, the variable resolver doesn't know the `before_text` (in this case, it's `<>\n\t`).
So we should provide the `before_text` for the variable resolver.
> Improve $TM_SELECTED_TEXT/$CLIPBOARD indentation

- plugin/vsnip.vim
Use unnamed register instead of @v.
Always yank, then reselect and feed 'c', not 'i' or 'a'.
Fixes #110.
> fix: cut/select operator

- autoload/vsnip/source/user_snippet.vim
These functions can be used if a plugin wants to get all paths where snippets are available.
> feat: expose functions to get snippet files

- autoload/vsnip/snippet.vim
- autoload/vsnip/snippet/node.vim
- autoload/vsnip/snippet/node/placeholder.vim
- autoload/vsnip/snippet/node/text.vim
- autoload/vsnip/snippet/node/variable.vim
Fixes #97, #105 
This PR aims to provide a detailed context for the traverse callback.
It can be useful for some situations.
Currently, The indentation fixing did not care about the base-indent of snippet's first-line.
- It makes the ability to avoid duplicate `a:node.text()` call.
Currently, the all tests are passed.
> Improve traverse

- plugin/vsnip.vim
It fixes this issue:
Test snippet:
```json
"try": {
"body": [
"try",
"\t$TM_SELECTED_TEXT$1",
"catch${2: /E${3:123:}/}$0",
"endtry"
],
"description": "try block",
"prefix": [
"try"
]
},
```
> fix: <BS> in select mode at end of line

- plugin/vsnip.vim
Fix update fails if snippet directory is in a symbolic link.
In source, calls `resolve()` at file reading, but autocmd doesn't call it, so I changed to call it.
> fix: can't refresh snippet inside a symlink

- plugin/vsnip.vim
Sometimes it fails to refresh snippets because it doesn't resolve the snippet directory (I have it symlinked).
> fix: resolve also snippet dir on VsnipOpen

- plugin/vsnip.vim
When register is set to "unnamedplus". It should be yanked to "+" register.
> use '+' register when clipboard set to unnamedplus

- plugin/vsnip.vim
Without this change, setting `vsnip_snippet_dir` to a filepath that is not expanded, i.e. `let g:vsnip_snippet_dir = "~/.vim/snippets"`, would lead to `:VsnipOpen` asking whether to create the directory or not - even if it exists.
> Expand g:vsnip_snippet_dir when checking existance

- autoload/vsnip/variable.vim
- doc/vsnip.txt
Transform filename to CamelCase format. Useful for class name.
`tmp/example/super_script.rb` => `SuperScript`
> Add `VIM_CAMELCASE_FILENAME` variable

- autoload/vsnip/session.vim
Hi. i solve this issue.
Fix https://github.com/hrsh7th/vim-vsnip/issues/226
explanation 
https://renenyffenegger.ch/notes/development/vim/script/vimscript/functions/strlen
strlen returns the number of bytes in a string, not the length of the string in characters
Use strchars to get the number character
> Fix #226 "Selection and non english words"

- autoload/vsnip/snippet.vim
- autoload/vsnip/snippet/node.vim
- autoload/vsnip/snippet/node/placeholder.vim
- autoload/vsnip/snippet/node/transform.vim
- autoload/vsnip/snippet/node/variable.vim
- autoload/vsnip/snippet/parser.vim
- spec/autoload/vsnip/snippet.vimspec
- Add missing `/camelcase` and `/pascalcase` from the [Grammar](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar).
- Support **whole word** transform
- supported regex: `(.*)` (i.e. the whole word)
- supported formats: `'/upcase' | '/downcase' | '/capitalize' | '/camelcase' | '/pascalcase'`
Related to: https://github.com/hrsh7th/vim-vsnip/issues/83#issuecomment-856075164 https://github.com/hrsh7th/vim-vsnip/issues/209
This helps with my React.js snippet;
```json
{
"useState": {
"prefix": "us",
"body": "const [${1:state}, set${1/(.*)/${1:/capitalize}/}] = useState(${2:initial${1/(.*)/${1:/capitalize}/}})$0",
"description": "hook: useState"
}
}
```
> Support whole word transform on tabstop and variable

- autoload/vsnip/session.vim
- misc/integration.json
- spec/plugin/vsnip.vimspec
This PR adds a fix to #228.
Using `strchars()` in [this line](https://github.com/hrsh7th/vim-vsnip/blob/39e41dca42c802ae655855dc816001ead8c0267b/autoload/vsnip/session.vim#L137) is correct, but `strlen()` should be used [here](https://github.com/hrsh7th/vim-vsnip/blob/39e41dca42c802ae655855dc816001ead8c0267b/autoload/vsnip/session.vim#L160) because `lsp_to_vim()` returns byteidx.
I also added tests for multibyte characters.
Since I'm not confident about tests, please fix if needed.
> Use strlen() instead of strchars() to avoid multibyte bug

- autoload/vsnip/variable.vim
- doc/vsnip.txt
Implement $RELATIVE_FILEPATH
As per docs in [VS Code](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables):
> `RELATIVE_FILEPATH` The relative (to the opened workspace or folder) file path of the current document
I've taken `to the opened workspace or folder` to mean current working directory in Vim-land.
> Implement $RELATIVE_FILEPATH

- plugin/vsnip.vim
Because "E716: Key not present in Dictionary" may appear.
> Add check for existence of 'user_data' in v:completed_item

- README.md
Follows up this PR https://github.com/hrsh7th/vim-vsnip-integ/pull/61. This PR is to update README.
> Update README for vim-easycomplete and remove obsoluted plugins

- .editorconfig
- .github/workflows/linux_neovim.yml
- README.md
- autoload/vital/_vsnip/VS/LSP/Diff.vim
- autoload/vital/_vsnip/VS/LSP/Position.vim
- autoload/vital/_vsnip/VS/LSP/Text.vim
- autoload/vital/_vsnip/VS/LSP/TextEdit.vim
- autoload/vital/_vsnip/VS/Vim/Buffer.vim
- autoload/vital/_vsnip/VS/Vim/Option.vim
- autoload/vsnip/indent.vim
- autoload/vsnip/parser/combinator.vim
- autoload/vsnip/range.vim
- autoload/vsnip/session.vim
- autoload/vsnip/snippet/node/transform.vim
- autoload/vsnip/snippet/node/variable.vim
- autoload/vsnip/snippet/parser.vim
- autoload/vsnip/source.vim
- autoload/vsnip/source/user_snippet.vim
- autoload/vsnip/source/vscode.vim
- autoload/vsnip/variable.vim
- lua/vsnip/treesitter.lua
- package.json
- plugin/vsnip.vim
This patch adds `treesitter` support.
It replaces standard behavior under `nvim` and if `nvim-treesitter` is installed.
It returns filetype for the code under the cursor, so embedded code is also processes correctly.
> Add `treesitter` integration

- autoload/vsnip/source.vim
- doc/vsnip.txt
- lua/vsnip/treesitter.lua
This patch allows to flexibly define snippets for injected languages.
Now `treesitter` filetype detector returns two filetypes:
1. filetype for code under the cutsor;
2. combined filetype for code under the cursor + parent code block (for injected language);
For example, for `lua` injected into `vim` script it will retirn:
```lua
{
filetype = "lua",
injected_filetype = "vim/lua",
}
```
This will allow users to configure snippets more flexibly. For example, if I want to add some snippets for `lua` code, injected into `vim`, for example  `vim.print( $1 )`, I will need to setup filetypes mapping like this:
```lua
vim.g.vsnip_filetypes = {
[ "vim/lua" ] = { "lua", "vim/lua" },
}
```
So for regular `lua` script `lua.json` snippets will be used, and for injected `vim/lua` - `lua.json` and …
> Refactor treesitter filetype detection
